# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cliclac}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stephane Bellity"]
  s.date = %q{2009-10-10}
  s.default_executable = %q{cliclac}
  s.description = %q{A port of CouchDB's Futon web interface to MongoDB. For more information, see http://www.github.com/sbellity/cliclac}
  s.email = %q{sbellity@gmail.com}
  s.executables = ["cliclac"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.homepage = %q{http://github.com/sbellity/cliclac}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{cliclac}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A port of CouchDB's Futon web interface to MongoDB}
  s.test_files = [
    "spec/cliclac/adapters/base_spec.rb",
     "spec/cliclac/adapters/mongo_spec.rb",
     "spec/cliclac/app_spec.rb",
     "spec/cliclac/helpers_spec.rb",
     "spec/cliclac/key_spec.rb",
     "spec/cliclac_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongo>, [">= 0.15"])
      s.add_runtime_dependency(%q<mongo_ext>, [">= 0.15"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0.9.4"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0.6.3"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.8"])
      s.add_development_dependency(%q<rack-test>, [">= 0.5.0"])
    else
      s.add_dependency(%q<mongo>, [">= 0.15"])
      s.add_dependency(%q<mongo_ext>, [">= 0.15"])
      s.add_dependency(%q<sinatra>, [">= 0.9.4"])
      s.add_dependency(%q<yajl-ruby>, [">= 0.6.3"])
      s.add_dependency(%q<rspec>, [">= 1.2.8"])
      s.add_dependency(%q<rack-test>, [">= 0.5.0"])
    end
  else
    s.add_dependency(%q<mongo>, [">= 0.15"])
    s.add_dependency(%q<mongo_ext>, [">= 0.15"])
    s.add_dependency(%q<sinatra>, [">= 0.9.4"])
    s.add_dependency(%q<yajl-ruby>, [">= 0.6.3"])
    s.add_dependency(%q<rspec>, [">= 1.2.8"])
    s.add_dependency(%q<rack-test>, [">= 0.5.0"])
  end
end
